dist: trusty
sudo: required
language: cpp


branches:
  only:
    - master


env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "wGhXwTBUERj3jzKFt87n4VCtVye7RJCPwW7Y3+Ly7ra/qO47ychNB7qpwff9Z0EkWaBPTKbHSt198GcxioifoQm7pEtgit7vBZVA8wojhB5RJfhd0qwC+x8qwvLkj10O4duqkxVpjqcsvjaKtmBnqvayZUpVyyPMUqmlW/MUZ3OaeoRhZtNd3LnaSayQ+I+gtY/4dhMlzHanRYt6TCwcKs2wWgmf7K0kuA2Cl8PhIJ4JoaUp/H4c+BRLsuI/nIA6vFUnPjJZnSX8H9dsFqJAu0KPrUzeSh43I7F7zGwAvrqaX3V4oJyPR/JrRjHf/kcF340nqygNXZAMXYyoz0QcjZZAVFIdEsqcFi2niQwjNUKw5uWe+47OlX347/u5zKI/fb/6//NNzBzT71xCGmVTvfkgDr5nJRZbOdcuY8yFhnwNeohczba0grh9jkIHOVOMzH6sKVhmFo79jv9Ql/T1yJejqASKAJTGTMSLpSfhIlskzrD3/PVMqJAK3VLwf7L47P9OcQ0iDsdlQ1V8S4GYT801V0YsSPTs7kRyqQTluvS5YFMoSNrGLhFYLx0YDpVpPumLITXY1HRlqfigxa61k7sQxSXShMF4aHa3qNdvTJ6FEqBHFnywQpaVsNBPQlkzyff9H+ClrYv4GgOBU+9yySGjQEyyEIkhK6H74znofbg="


matrix:
  include:    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7 BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7 BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=g++-8 BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=g++-8 BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0 BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0 BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang++-6.0 BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang++-6.0 BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env: COMPILER=clang++-7 BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env: COMPILER=clang++-7 BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        coverity_scan:
          project:
            name: "Vitaliy-Grigoriev/Protocol-Analyzer"
            description: "Fuzz testing framework for network protocols."
            version: 0.0.10
          notification_email: Vit.link420@gmail.com
          build_command_prepend: cov-configure --comptype gcc --compiler gcc-7 --template && cmake -j4 .
          build_command: make -j 4
          branch_pattern: master
      env: COMPILER=g++-7 BUILD_TYPE=Debug

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update


install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/DEPS"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ..
  - sudo apt-get install -qq libssl-dev
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90


script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
      then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi

  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - uname -a
  - cmake --version
  - ${COMPILER} --version
  - bash build_travis.sh


notifications:
  email:
    on_failure: always
    on_success: never
